# -*- coding: utf-8 -*-
"""Untitled78.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifN9xbbAHw5g3DBSZOFOZnAR4tk9e_Gr

# **Name:Rana Essam Hassanen**
# **Task 3 : Exploratory Analysis On Terrorism**
"""

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Importing the dataset**"""

data=pd.read_csv("globalterrorismdb_0718dist.csv", encoding="latin1")
df=pd.DataFrame(data)
print("Data uploaded successfully")
df.head(5)

df.isnull().sum()

df.describe()

print("*******************************")
df.columns

df=df[["iyear","imonth","iday","country_txt","region_txt","provstate","city",
       "latitude","longitude","location","summary","attacktype1_txt","targtype1_txt",
       "gname","motive","weaptype1_txt","nkill","nwound","addnotes"]]
df.head()

df.isnull().sum()

df["nkill"]=df["nkill"].fillna(0)
df["nwound"]=df["nwound"].fillna(0)
df["total_victims"]=df["nkill"]+df["nwound"]

number_of_attacks=df["iyear"].value_counts(dropna=False).sort_index(axis=0).to_frame().reset_index().rename(columns={"index":"iyear","iyear":"Attacks"}).set_index("iyear")
number_of_attacks.describe
victims_years=df[["iyear","total_victims"]].sum()
victims_years.head()

"""# **Visualization**
--> **Number Of Attacks Through The Years**
"""

number_of_attacks.plot(kind="bar",color="pink",figsize=(12,5),fontsize=13)
plt.title("Through the years",fontsize=12)
plt.xlabel("iyear",fontsize=12)
plt.ylabel("Number of Attacks",fontsize=12)
plt.show()

"""# --> **Number of victims through the years**"""

victims_years.plot(kind="bar",color="yellow",figsize=(15,6))
plt.title("Victims Through The years",fontsize=13)
plt.xlabel("Years",fontsize=13)
plt.xticks(fontsize=12)
plt.ylah

num_killed=df[["iyear","nkill"]].groupby("iyear").sum()
num_killed.head()

num_wounded=df[["iyear","nwound"]].groupby("iyear").sum()
num_wounded.head()

"""# --> **Number of the killed Vs the wounded through the years**"""

fig=plt.figure()
ax0=fig.add_subplot(2,1,1)
ax1=fig.add_subplot(2,1,2)

#Killed
num_killed.plot(kind="bar",color="",figsize=(15,15),ax=ax0)
ax0.set_title("People Killed in each Year")
ax0.set_xlabel("iyear")
ax0.set_ylabel("Number of People Killed") 

#Wounded
num_wounded.plot(kind="bar",color="green",figsize=(15,15),ax=ax1)
ax1.set_title("People Wounded in each Year")
ax1.set_xlabel("iyear")
ax1.set_ylabel("Number of People Wounded")

plt.show()

ct=df["country_txt"].value_counts().head(10)
ct

"""# **--> Number of attacks in each country**"""

ct.plot(kind="bar",color="m",figsize=(15,6))
plt.title("Country",fontsize=13)
plt.xlabel("country_txt",fontsize=13)
plt.xticks(fontsize=12)
plt.ylabel("Number of Attacks",fontsize=13)
plt.show()

grp=df["gname"].value_counts()[1:10]
grp

"""# --> **Number of attacks of each group for terrorism**"""

grp.plot(kind="bar",color="r",figsize=(15,6))
plt.title("Group wise Attacks",fontsize=13)
plt.xlabel("Terrorist Groups",fontsize=13)
plt.xticks(fontsize=12)
plt.ylabel("Number of Attacks",fontsize=13)
plt.show()

cc=df[["city","total_victims"]].groupby("city").sum().sort_values(by="total_victims",ascending=False).drop("Unknown")
cc.head(10)

"""# --> **Country with the most victims**"""

cc.head(10).plot(kind="bar",color="c",figsize=(12,6))
plt.title("Countries with most victims",fontsize=13)
plt.xlabel("(Countries)",fontsize=13)
plt.xticks(fontsize=10)
plt.ylabel("Number of Victims",fontsize=13)
plt.show()

ak=df[["attacktype1_txt","nkill"]].groupby("attacktype1_txt").sum().sort_values(by="nkill",ascending=False)
aw=df[["attacktype1_txt","nwound"]].groupby("attacktype1_txt").sum().sort_values(by="nwound",ascending=False)

reg=pd.crosstab(df.iyear,df.region_txt)

"""# --> **Regions with the attacks**"""

reg.plot(kind="area", stacked=False, alpha=0.5,figsize=(15,8))
plt.title("Region wise attacks",fontsize=20)
plt.xlabel("Years",fontsize=20)
plt.ylabel("Number of Attacks",fontsize=20)
plt.show()

"""# --> **People who killed , wounded in each attack type**"""

fig=plt.figure()
ax0=fig.add_subplot(1,2,1)
ax1=fig.add_subplot(1,2,2)

#Killed
ak.plot(kind="bar",color="cornflowerblue",figsize=(15,6),ax=ax0)
ax0.set_title("People Killed in each Attack Type")
ax0.set_xlabel("Attack Types")
ax0.set_ylabel("Number of people Killed")

#Wounded
aw.plot(kind="bar",color="cornflowerblue",figsize=(15,6),ax=ax1)
ax1.set_title("People Wounded in each Attack Type")
ax1.set_xlabel("Attack Types")
ax1.set_ylabel("Number of people Wounded")
plt.show()